### ISSUE TITLE
Remove all console output in production website

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#14]
Your console window should not output any message for the production website

**Comment by hmasum52** [comment]
This issue is solved in the latest production deployment. Please verify it on the [production site](https://badhan-datainput.netlify.app/#/home).

Note that there is still some console log for failed HTTP API calls. I don't know how to remove them yet😕. Hope I can remove them in a future deployment.  

![image](https://user-images.githubusercontent.com/55390870/164779411-5cf8778f-1c6f-49c5-b170-66035345f38b.png)
