### ISSUE TITLE
Reloading after logging out causes errors

### ISSUE THREAD

**Issue by mirmahathir1** [Badhan-BUET-Zone/badhan-datainput#24]
I think you may have forgotten to clear the token from your storage after logging out. The ss below should provide you insight of what I mean-
![Screenshot (13)](https://user-images.githubusercontent.com/36355905/164783394-8968229f-0ae8-4ccd-a29c-01f7d3f211af.png)
![Screenshot (14)](https://user-images.githubusercontent.com/36355905/164783407-f4243d04-2b9a-40bc-893a-b9d74a0185cb.png)
![Screenshot (15)](https://user-images.githubusercontent.com/36355905/164783410-a691d5d3-6951-4b14-b921-7537dc77c240.png)
![Screenshot (16)](https://user-images.githubusercontent.com/36355905/164783421-9de1c529-5cd7-4ba0-a872-69387edf8d92.png)

**Comment by hmasum52** [comment]
### This issue is fixed now. Please verify it on the test site.

I was clearing from the local storage but at the same time was calling the redirect API with an empty token. I hope the ss below clears it. 
### Local storage before logout 
![image](https://user-images.githubusercontent.com/55390870/164792286-082eaf04-9e68-4a3b-8489-1a8667c06a91.png)
### Local storage after logout 
![image](https://user-images.githubusercontent.com/55390870/164792322-c485bbea-a2f8-4a3c-a88d-7703ec363a0a.png)
